-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 13:42:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema netsearch_db
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema netsearch_db
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `netsearch_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `netsearch_db` ;

-- -----------------------------------------------------
-- Table `netsearch_db`.`switches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netsearch_db`.`switches` ;

CREATE TABLE IF NOT EXISTS `netsearch_db`.`switches` (
  `id_switches` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `ip` INT NULL,
  PRIMARY KEY (`id_switches`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netsearch_db`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netsearch_db`.`rooms` ;

CREATE TABLE IF NOT EXISTS `netsearch_db`.`rooms` (
  `id_rooms` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  PRIMARY KEY (`id_rooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netsearch_db`.`port_connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netsearch_db`.`port_connections` ;

CREATE TABLE IF NOT EXISTS `netsearch_db`.`port_connections` (
  `id_port_connections` INT NOT NULL AUTO_INCREMENT,
  `switch` INT NULL,
  `room` INT NULL,
  `port` INT NULL,
  PRIMARY KEY (`id_port_connections`),
  INDEX `fk_switch_idx` (`switch` ASC) VISIBLE,
  INDEX `fk_room_idx` (`room` ASC) VISIBLE,
  CONSTRAINT `fk_switch`
    FOREIGN KEY (`switch`)
    REFERENCES `netsearch_db`.`switches` (`id_switches`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room`
    FOREIGN KEY (`room`)
    REFERENCES `netsearch_db`.`rooms` (`id_rooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netsearch_db`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netsearch_db`.`devices` ;

CREATE TABLE IF NOT EXISTS `netsearch_db`.`devices` (
  `id_devices` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `mac` VARCHAR(17) NULL,
  PRIMARY KEY (`id_devices`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
