-- MySQL Script generated by MySQL Workbench
-- Thu Dec  5 14:40:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema netsearch_db
-- -----------------------------------------------------
-- 
-- 
DROP SCHEMA IF EXISTS `netsearch_db` ;

-- -----------------------------------------------------
-- Schema netsearch_db
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `netsearch_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `netsearch_db` ;

-- -----------------------------------------------------
-- Table `netsearch_db`.`switches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netsearch_db`.`switches` ;

CREATE TABLE IF NOT EXISTS `netsearch_db`.`switches` (
  `id_switch` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `ip` INT UNSIGNED NULL,
  PRIMARY KEY (`id_switch`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netsearch_db`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netsearch_db`.`rooms` ;

CREATE TABLE IF NOT EXISTS `netsearch_db`.`rooms` (
  `id_room` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  PRIMARY KEY (`id_room`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netsearch_db`.`port_connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netsearch_db`.`port_connections` ;

CREATE TABLE IF NOT EXISTS `netsearch_db`.`port_connections` (
  `id_port_connection` INT NOT NULL AUTO_INCREMENT,
  `switch_id` INT NULL,
  `room_id` INT NULL,
  `port` INT NULL,
  PRIMARY KEY (`id_port_connection`),
  INDEX `fk_switch_idx` (`switch_id` ASC),
  INDEX `fk_room_idx` (`room_id` ASC),
  CONSTRAINT `fk_switch`
    FOREIGN KEY (`switch_id`)
    REFERENCES `netsearch_db`.`switches` (`id_switch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `netsearch_db`.`rooms` (`id_room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netsearch_db`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netsearch_db`.`devices` ;

CREATE TABLE IF NOT EXISTS `netsearch_db`.`devices` (
  `id_device` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `mac` VARCHAR(17) NULL,
  PRIMARY KEY (`id_device`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
